export const PROTAGONISTS = [
  {
    id: 'soledad',
    name: 'Soledad Ramírez',
    age: '22 años',
    nationality: 'Española',
    description: 'Joven de apariencia tranquila que retoma sus estudios en la Universidad Somnia. Observa más de lo que deja ver.',
    landingBio: 'He vuelto a la Universidad Somnia para terminar lo que dejé a medias. Dicen que soy tranquila, pero es solo que prefiero observar antes de hablar. Hay caras conocidas por aquí... y no todas me alegran igual.',
    creator: 'saramarillo',
    avatar: '/assets/sprites/soledad/arc1_happy.png',
    color: 'var(--color-soledad)',
    available: true,
    looks: [
      { id: 'arc1', description: 'Pelo largo castaño', episodes: '1–13' },
      { id: 'arc2', description: 'Pelo corto (se lo corta en ep. 14)', episodes: '14+' },
    ],
  },
  {
    id: 'ayla',
    name: 'Ayla Solberg',
    age: '21 años',
    nationality: 'Noruega',
    description: 'Estudiante de arte y arqueología. Porte elegante, mirada serena y un ligero acento nórdico.',
    landingBio: 'Estudio arte y arqueología, aunque a veces siento que investigo más a las personas que a las piedras. Vengo de lejos, pero esta ciudad empieza a sentirse menos extraña de lo que esperaba.',
    creator: 'isaweakness',
    avatar: '/assets/sprites/ayla/arc1_happy.png',
    color: 'var(--color-ayla)',
    available: true,
  },
]

export const NPC_CHARACTERS = [
  {
    id: 'ethan',
    name: 'Ethan',
    role: 'Líder del Club Paranormal',
    avatar: '/assets/avatars/Ethan.png',
    color: 'var(--color-ethan)',
    expressions: ['neutral', 'happy', 'blush', 'sad', 'surprised', 'angry'],
    looks: [
      { id: 'arc1', description: 'Pelo azul azabache', episodes: '1–12' },
      { id: 'arc2', description: 'Pelo negro (cambio de look ep. 13)', episodes: '13+' },
    ],
  },
  {
    id: 'ryan',
    name: 'Ryan',
    role: 'Trabajador de bar',
    avatar: '/assets/avatars/Ryan.png',
    color: 'var(--color-ryan)',
    expressions: ['neutral', 'happy', 'blush', 'sad', 'surprised', 'angry'],
  },
  {
    id: 'lydia',
    name: 'Lydia',
    role: 'Compañera de cuarto de Ayla',
    avatar: '/assets/avatars/Lydia.png',
    color: 'var(--color-lydia)',
    expressions: ['neutral', 'happy', 'blush', 'sad', 'surprised', 'angry'],
  },
  {
    id: 'frey',
    name: 'Frey',
    role: 'Policía',
    avatar: '/assets/avatars/Frey.png',
    color: 'var(--color-frey)',
    expressions: ['neutral', 'happy', 'blush', 'sad', 'surprised', 'angry'],
  },
  {
    id: 'grace',
    name: 'Grace',
    role: '???',
    avatar: '/assets/avatars/Grace.png',
    color: 'var(--color-grace)',
    expressions: ['neutral', 'happy', 'blush', 'sad', 'angry', 'silueta'],
    alwaysMystery: true,
  },
  {
    id: 'sappire',
    name: 'Sappire',
    role: 'Compañera de cuarto de Maven',
    avatar: '/assets/avatars/Shapphire.png',
    color: 'var(--color-sappire)',
    expressions: ['neutral', 'happy', 'blush', 'sad', 'surprised', 'angry'],
  },
  {
    id: 'xavier',
    name: 'Xavier de Crimson',
    role: '???',
    avatar: '/assets/avatars/Xavier.png',
    color: 'var(--color-xavier)',
    expressions: ['neutral', 'happy', 'blush', 'sad', 'surprised', 'angry'],
  },
  {
    id: 'luna',
    name: 'Luna',
    role: 'Astraea',
    avatar: '/assets/avatars/Luna.png',
    color: 'var(--color-luna)',
    expressions: ['neutral', 'happy', 'blush', 'sad', 'surprised', 'angry'],
  },
  {
    id: 'aurora',
    name: 'Aurora',
    role: '???',
    avatar: '/assets/avatars/Aurora.png',
    color: 'var(--color-aurora)',
    expressions: ['neutral', 'happy', 'blush', 'sad', 'surprised', 'angry'],
  },
  {
    id: 'dani',
    name: 'Dani',
    role: '???',
    avatar: '/assets/avatars/Dani.png',
    color: 'var(--color-dani)',
    expressions: ['neutral', 'happy', 'blush', 'sad', 'surprised', 'angry'],
  },
  {
    id: 'estrella',
    name: 'Estrella',
    role: '???',
    avatar: '/assets/avatars/Estrella.png',
    color: 'var(--color-estrella)',
    expressions: ['neutral', 'happy', 'blush', 'sad', 'angry'],
  },
  {
    id: 'leo',
    name: 'Leo',
    role: '???',
    avatar: '/assets/avatars/Leo.png',
    color: 'var(--color-leo)',
    expressions: ['neutral', 'happy', 'blush', 'sad', 'surprised', 'angry'],
  },
  {
    id: 'noa',
    name: 'Noa',
    role: 'Abre portales — compañero de Frey',
    avatar: '/assets/avatars/Noa.png',
    color: 'var(--color-noa)',
    expressions: ['neutral', 'happy', 'blush', 'sad', 'surprised', 'angry'],
    isChild: true,
  },
  {
    id: 'ona',
    name: 'Ona',
    role: 'Facción de Erebo',
    avatar: '/assets/avatars/Ona.png',
    color: 'var(--color-ona)',
    expressions: ['neutral', 'happy', 'blush', 'sad', 'surprised', 'angry'],
  },
  {
    id: 'apolo',
    name: 'Apolo',
    role: 'Dios — solo perceptible por Soledad',
    avatar: '/assets/avatars/Apolo.png',
    color: 'var(--color-apolo)',
    expressions: ['neutral', 'happy', 'blush', 'sad', 'surprised', 'angry'],
    protagonistOnly: 'soledad',
    spriteSize: 'small',
  },
  {
    id: 'lucas',
    name: 'Lucas',
    role: '???',
    avatar: '/assets/avatars/Lucas.png',
    color: 'var(--color-lucas)',
    expressions: ['neutral', 'happy', 'blush', 'sad', 'surprised', 'angry'],
  },
  {
    id: 'madre',
    name: 'Victoria',
    role: 'Madre de Soledad',
    avatar: '/assets/sprites/madre/arc1.png',
    color: 'var(--color-madre)',
    expressions: ['neutral', 'happy', 'sad', 'angry', 'emocionada'],
  },
  {
    id: 'padre',
    name: 'Javier',
    role: 'Padre de Soledad',
    avatar: '/assets/sprites/padre/arc1.png',
    color: 'var(--color-padre)',
    expressions: ['neutral', 'happy', 'sad', 'angry'],
  },
  {
    id: 'hermana_luna',
    name: 'Luna',
    role: 'Hermana de Soledad',
    avatar: '/assets/avatars/Luna.png',
    color: 'var(--color-hermana-luna)',
    expressions: ['neutral'],
  },
  {
    id: 'policia',
    name: 'Policía',
    role: 'Comisaría de Guadalajara',
    avatar: '/assets/sprites/policia/arc1.png',
    color: 'var(--color-policia)',
    expressions: ['neutral'],
  },
  {
    id: 'silueta_hombre',
    name: 'Policía',
    role: 'NPC de paso',
    avatar: '/assets/sprites/silueta_hombre/arc1.png',
    color: 'var(--color-policia)',
    expressions: ['neutral'],
  },
  {
    id: 'silueta_mujer',
    name: 'Comisaria',
    role: 'Comisaría de Guadalajara',
    avatar: '/assets/sprites/silueta_mujer/arc1.png',
    color: 'var(--color-policia)',
    expressions: ['neutral'],
  },
]
