export const GALLERY_IMAGES = [
  {
    id: 'ethan_cafeteria_soledad',
    file: 'gallery_soledad/gallery_Soledad_1-1.png',
    title: 'La cafetería',
    subtitle: 'con Ethan',
    routes: ['soledad'],
    episode: 1,
  },
  {
    id: 'ryan_crucigrama',
    file: 'gallery_soledad/gallery_Soledad_1-2.png',
    title: 'El crucigrama',
    subtitle: 'con Ryan',
    routes: ['soledad'],
    episode: 1,
  },
  {
    id: 'ryan_cafe_soledad',
    file: 'gallery_soledad/gallery_Soledad_2-1.png',
    title: 'El café',
    subtitle: 'con Ryan',
    routes: ['soledad'],
    episode: 2,
  },
  {
    id: 'ryan_moto_parada',
    file: 'gallery_soledad/gallery_Soledad_2-2.png',
    title: 'Parada en moto',
    subtitle: 'con Ryan',
    routes: ['soledad'],
    episode: 2,
  },
  {
    id: 'ethan_cafeteria_ayla',
    file: 'gallery_ayla/gallery_Ayla_1-1.png',
    title: 'La cafetería',
    subtitle: 'con Ethan',
    routes: ['ayla'],
    episode: 1,
  },
  {
    id: 'lydia_plantas',
    file: 'gallery_ayla/gallery_Ayla_1-2.png',
    title: 'Las plantas',
    subtitle: 'con Lydia',
    routes: ['ayla'],
    episode: 1,
  },
  {
    id: 'lydia_ayla_desayuno',
    file: 'gallery_ayla/gallery_Ayla_2-1.png',
    title: 'Desayuno con Lydia',
    subtitle: 'en la residencia',
    routes: ['ayla'],
    episode: 2,
  },
  {
    id: 'frey_ayla_rescate',
    file: 'gallery_ayla/gallery_Ayla_2-2.png',
    title: 'El rescate',
    subtitle: 'con Frey',
    routes: ['ayla'],
    episode: 2,
  },
  {
    id: 'cadaveres_luces',
    file: 'gallery_soledad/gallery_Soledad_3-1.png',
    title: 'Siete cuerpos',
    subtitle: 'en la discoteca',
    routes: ['soledad'],
    episode: 3,
  },
  {
    id: 'grace_hilos_dj',
    file: 'gallery_soledad/gallery_Soledad_3-2.png',
    title: 'Hilos azules',
    subtitle: 'con Grace',
    routes: ['soledad'],
    episode: 3,
  },
  {
    id: 'ryan_soledad_casa',
    file: 'gallery_soledad/gallery_Soledad_3-3.png',
    title: 'Te llevo a casa',
    subtitle: 'con Ryan',
    routes: ['soledad'],
    episode: 3,
  },
  {
    id: 'selfie_tres_fiesta',
    file: 'gallery_ayla/gallery_Ayla_3-1.png',
    title: 'El selfie',
    subtitle: 'con Lydia y Soledad',
    routes: ['ayla'],
    episode: 3,
  },
  {
    id: 'ayla_grace_nevera',
    file: 'gallery_ayla/gallery_Ayla_3-2.png',
    title: 'El rescate',
    subtitle: 'con Grace',
    routes: ['ayla'],
    episode: 3,
  },
  {
    id: 'frey_ayla_cama',
    file: 'gallery_ayla/gallery_Ayla_3-3.png',
    title: 'El beso en la frente',
    subtitle: 'con Frey',
    routes: ['ayla'],
    episode: 3,
  },
]

export function getGalleryImage(id) {
  return GALLERY_IMAGES.find((img) => img.id === id) ?? null
}
